site_name: Petstore API
site_description: Reference rendering for mkdocs-openapi
site_dir: ../../site
use_directory_urls: false

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags
  - openapi:
      output_dir: api-reference
      models_dir: models

nav:
  - Overview: index.md
  - API Reference: openapi/spec.json

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

validation:
  nav:
    omitted_files: warn
    absolute_links: warn
  links:
    absolute_links: relative_to_docs
    unrecognized_links: warn
