site_name: Multiple API references
docs_dir: docs
site_dir: site

theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - search
  - openapi:
      specs:
        pets:
          source: openapi/pets.yaml
          output_dir: api-reference/pets
        orders:
          source: openapi/orders.yaml
          output_dir: api-reference/orders
          models_dir: api-reference/orders/data-models
          models_title: Order models

nav:
  - Home: index.md
  - APIs:
      - Pets: openapi/pets.yaml
      - Orders: openapi/orders.yaml

validation:
  nav:
    omitted_files: warn
  links:
    unrecognized_links: warn
